version: '3'

services:

  shellcheck:
    build:
      context: ./shellcheck
    volumes:
      - ./:/usr/local/src/bash-commons
    working_dir: /usr/local/src/bash-commons/shellcheck
    command: ./shellcheck.sh

  bats:
    build:
      context: ./bats
    volumes:
      # Mount all the files so you have "hot reload" of all changes from the host
      - ./:/usr/local/src/bash-commons
    working_dir: /usr/local/src/bash-commons
    command: bats test
    # Necessary so we can run a mock EC2 metadata service on port 80 on a special IP
    privileged: true
    ports:
      # For moto
      - "5000:5000"
      # For ec2-metadata-mock
      - "8111:8111"
